base_configs = ["../../../replogle/common/base.toml", "../../../replogle/data/source/zeroshot_rpe1.toml", "../../../replogle/data/views/state_latent_hvg.toml", "../../../replogle/model/film_latent_diffusion.toml", "../../../replogle/training/stage2.toml"]

[experiment]
name = "replogle_zeroshot_rpe1_stage2"
output_dir = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/rpe1/stage2"

[vae]
checkpoint_path = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/rpe1/stage1/vae_checkpoints/latest.pt"
