base_configs = ["./infer.toml"]

[experiment]
name = "replogle_zeroshot_hepg2_infer_v1"
output_dir = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/hepg2/infer_v1_ddim50"

[checkpoint]
path = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/hepg2/stage2_unfrozen_vae_v1/checkpoints/latest.pt"
use_ema = false

[output]
prediction_path = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/hepg2/infer_v1_ddim50/predictions.h5ad"

[cell_eval]
outdir = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/hepg2/infer_v1_ddim50/cell_eval"

[diffusion]
timestep_respacing = "ddim50"
