base_configs = ["../../../replogle/common/base.toml", "../../../replogle/data/source/fewshot_jurkat.toml", "../../../replogle/data/views/state_latent_hvg.toml", "../../../replogle/model/film_latent_diffusion.toml", "../../../replogle/training/stage1.toml"]

[experiment]
name = "replogle_fewshot_jurkat_stage1"
output_dir = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_fewshot/jurkat/stage1"
