base_configs = ["../../../replogle/common/base.toml", "../../../replogle/data/source/fewshot_jurkat.toml", "../../../replogle/data/views/state_latent_hvg.toml", "../../../replogle/model/film_latent_diffusion.toml", "../../../replogle/training/stage2.toml"]

[experiment]
name = "replogle_fewshot_jurkat_stage2"
output_dir = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_fewshot/jurkat/stage2"

[vae]
checkpoint_path = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_fewshot/jurkat/stage1/vae_checkpoints/latest.pt"
