base_configs = ["../../../replogle/inference/base.toml"]

[experiment]
name = "replogle_fewshot_jurkat_infer"
output_dir = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_fewshot/jurkat/infer"

[checkpoint]
# Replace <final_diffusion_stage> with stage2 or stage2_unfrozen_vae.
path = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_fewshot/jurkat/<final_diffusion_stage>/checkpoints/latest.pt"

[input.split]
dataset_config_path = "../../../replogle/data/source/fewshot_jurkat.toml"

[output]
prediction_path = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_fewshot/jurkat/infer/predictions.h5ad"

[cell_eval]
outdir = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_fewshot/jurkat/infer/cell_eval"
