base_configs = ["../base.toml"]

[experiment]
name = "replogle_zeroshot_k562_infer"
output_dir = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/k562/infer"

[checkpoint]
# Replace <final_diffusion_stage> with stage2 or stage2_unfrozen_vae.
path = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/k562/<final_diffusion_stage>/checkpoints/latest.pt"

[input.split]
dataset_config_path = "../../../replogle/data/source/zeroshot_k562.toml"

[output]
prediction_path = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/k562/infer/predictions.h5ad"

[cell_eval]
outdir = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/k562/infer/cell_eval"
