base_configs = ["./infer.toml"]

[experiment]
name = "replogle_zeroshot_k562_infer_v1"
output_dir = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/k562/infer_v1"

[checkpoint]
path = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/k562/stage2_unfrozen_vae_v1/checkpoints/latest.pt"

[output]
prediction_path = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/k562/infer_v1/predictions.h5ad"

[cell_eval]
outdir = "/work/home/cryoem666/xyf/temp/pycharm/PerturbNova/outputs/replogle_zeroshot/k562/infer_v1/cell_eval"
